Improve the namespace store docs
noobaa/noobaa-operator pull request #1065
Opened 2023-02-27 20:50 UTC by Neon-White

### Explain the changes
1. Improved the namespace store documentation

Please note that `Store Secret Creation` was added in #1064 

- [x] Doc added/updated

2023-03-13 07:40 UTC, Sheetalpamecha requested changes

2023-03-13 07:40 UTC, Sheetalpamecha commented on doc/namespace-store-crd.md
> +noobaa -n noobaa namespacestore create google-cloud-storage <NAMESPACESTORE NAME> --private-key-json-file <PATH TO credentials.json>
Missed the --target-bucket field here.

2023-03-29 12:48 UTC, baum approved these changes
lgtm 🖖

2023-04-16 07:30 UTC, shirady commented on doc/namespace-store-crd.md
I think you can add here `AWS-S3 Security Token Service (STS)` as you did in #1064.

2023-04-28 09:33 UTC, merged