Noobaa bucket quota alerts are not working
noobaa/noobaa-operator pull request #1067
Opened 2023-03-02 12:01 UTC by v-harihar

### Explain the changes
Prometheus-rules.yaml should be updated according to https://github.com/noobaa/noobaa-mixins/pull/23

The tag "Noobaa_bucket_quota" has been changed to
"Noobaa_bucket_size_quota" in noobaa-mixins and reflecting the same into noobaa-operator in this PR

### Testing Instructions:
Steps to Reproduce:
1. Create bucket in NooBaa and set capacity quota to 2 GB (RPC call {'name': '<bucket-name>', 'quota': 
{'unit': 'GIGABYTE', 'size': 2}}).
2. Upload 5 files with size 500MB into the bucket.
3. Check alerts in ODF Monitoring.

OR

This patch can be tested with the following TC https://github.com/red-hat-storage/ocs-ci/blob/b28dfcd0e3f7fcf624d6590dd40255821058fbf7/tests/manage/monitoring/prometheus/test_noobaa.py#L21

- [ ] Doc added/updated
- [ ] Tests added

2023-03-02 12:58 UTC, liranmauda commented
Hi @v-harihar 
It seems that https://github.com/noobaa/noobaa-mixins/pull/23 added more there and changed also the names. 
Please make sure that we are not missing any of those changes. 

@dannyzaken changing the alert name can effect ODF UI.

2023-03-05 16:32 UTC, dannyzaken approved these changes

2023-03-05 16:34 UTC, dannyzaken commented
@v-harihar you need to commit the changes in `deploy.go`. This is what failing the tests

2023-03-06 08:38 UTC, nimrod-becker approved these changes

2023-03-06 09:29 UTC, liranmauda requested changes
@dannyzaken @nimrod-becker any reason why not carry all Igor's changes with this PR? 
https://github.com/noobaa/noobaa-operator/pull/1067#issuecomment-1451828250

2023-03-06 09:40 UTC, v-harihar commented
> @dannyzaken @nimrod-becker any reason why not carry all Igor's changes with this PR? [#1067 (comment)](https://github.com/noobaa/noobaa-operator/pull/1067#issuecomment-1451828250)

Apologies. I missed your comment.

2023-03-06 10:54 UTC, liranmauda approved these changes

2023-03-06 13:43 UTC, merged