Adding mongodb-url flag that can change the url of mongo, enabling to connect to a remote mongodb
noobaa/noobaa-operator pull request #395
Opened 2020-08-20 10:42 UTC by liranmauda

- Adding mongodb-url flag that can change the URL of mongo, enabling to connect to a remote mongodb
- Skipping create of db pod when given an external db URL

Expecting URL in the form of:  `mongodb://<ip>:<port>/<db>`

Fixes: #304

2020-12-07 10:56 UTC, liranmauda commented
Moving to draft.
After talking with @lallinger-arbeit and @QuintinBecker we might want to drop this effort

2021-02-10 09:08 UTC, lallinger-arbeit commented
@liranmauda could you do me a favour and rebase this? we are still using this and currently i am always rebasing this myself, but it gets harder for me to do it correctly with more and more changes...

2021-02-10 09:26 UTC, liranmauda commented
> @liranmauda could you do me a favour and rebase this? we are still using this and currently i am always rebasing this myself, but it gets harder for me to do it correctly with more and more changes...

Are you using it? 
I will rebase.

2021-02-10 09:32 UTC, lallinger-arbeit commented
> Are you using it?
yes, with the HA setup described [here](https://github.com/noobaa/noobaa-operator/issues/481)
> I will rebase.
thank you very much!

2021-02-10 10:26 UTC, liranmauda commented
Done, Hopefully I didn't miss anything :) 
@lallinger-arbeit Can you test it?

2021-02-10 10:37 UTC, lallinger-arbeit commented
Perfect, thanks! I will test it immediately!

2021-02-10 12:07 UTC, lallinger-arbeit commented
@liranmauda seems to be not right yet, noobaa-core does not get the set mongoDbURL, but the endpoints do:
![grafik](https://user-images.githubusercontent.com/54403915/107508102-d0fb4680-6ba0-11eb-8b57-9653efb983a6.png)
![grafik](https://user-images.githubusercontent.com/54403915/107508176-ea9c8e00-6ba0-11eb-9469-24f02ae719f3.png)

2021-02-10 12:15 UTC, lallinger-arbeit commented
The attempts field now shows up as desired. Thinking about it i think it would be more straightforward if the field would be called `Retries` instead of `Attempts`. As attempts=0 would mean the trigger shouldn't be run... If you rename it to retries i would suggest the following tooltip: "Number of retries Noobaa will make if the trigger fails"

2021-02-10 16:25 UTC, liranmauda commented
pushed a fix.
Changing to "ready for review"

2021-02-11 08:14 UTC, dannyzaken requested changes

2021-02-11 08:14 UTC, dannyzaken commented on pkg/system/phase2_creating.go
> +		if err := r.ReconcileDB(); err != nil {
ReconcileDB also reconciles postgres. you should only refer to `MongoDbURL` when dealing with mongo. I think for now you can verify in phase1 that if `MongoDbURL` is passed then the `DB_TYPE` must be mongo. later on, we might need to handle the migration from external mongo to postgres, where the db-type is postgres and there is a mongoURL

2021-02-11 11:30 UTC, lallinger-arbeit commented
> 
> 
> pushed a fix.

working as inteded now, thanks @liranmauda :)

2021-02-11 11:48 UTC, dannyzaken approved these changes

2021-02-11 12:00 UTC, merged