setting upgrade job restartPolicy to never
noobaa/noobaa-operator pull request #584
Opened 2021-03-17 14:14 UTC by dannyzaken

* setting `restartPolicy` to never will keep failed pods around so we can examine the failures
* setting `backoffLimit` to 4 (default is 6) to reduce the number of pods that can potentially stay in the NS
* one thing to notice is that failed runs will leave a pod (not running) with ERROR state. This can lead to support cases, but maybe these are cases we want to know about

Signed-off-by: Danny Zaken <dannyzaken@gmail.com>

2021-03-17 14:30 UTC, nimrod-becker approved these changes

2021-03-18 13:06 UTC, nimrod-becker approved these changes

2021-03-18 13:55 UTC, jackyalbo requested changes

2021-03-18 13:55 UTC, jackyalbo commented on pkg/system/phase2_creating.go
>  	r.setDesiredCoreEnv(&r.UpgradeJob.Spec.Template.Spec.Containers[0])
move this before the added code (line 1004) - so the two parts will be better divided

2021-03-21 08:34 UTC, jackyalbo approved these changes

2021-03-21 10:00 UTC, merged