noobaa-mgmt and s3 LoadBalancer service ports
noobaa/noobaa-operator pull request #647
Opened 2021-06-06 08:56 UTC by baum

Issue statement
============
Both s3 and noobaa-mgmt LoadBalancer services request ports 80 and 443.
Given a single external LoadBalancer external IP available in the cluster
both services clash.

Test
============

noobaa CLI install:
*    `noobaa install --mini -n noobaa`
*    `kubectl get svc -n noobaa`

k8s cluster
========

[Docker Desktop Kubernetes](https://docs.docker.com/desktop/kubernetes/)

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>

2021-06-06 09:14 UTC, guymguym requested changes
Can you elaborate - when does a cluster have a "Single LoadBalancer external IP" ?
Is it a general issue that services should not repeat the same ports as other services in the entire cluster ??

I think that we assume the S3 port is 80/443 on the service - if I run an application in the cluster that connects to s3.noobaa.svc I certainly expect it.

2021-06-06 12:18 UTC, baum commented
@guymguym  stumbled upon this issue after deploying noobaa on [Docker Desktop Kubernetes](https://docs.docker.com/desktop/kubernetes/). In that environment S3 HTTP/HTTPS services are not accessible from outside the cluster, since the s3 LoadBalancer service is hidden by the noobaa-mgmt one, see the [the commit message](https://github.com/noobaa/noobaa-operator/pull/647/commits/b04fa17417255b529fc9cc7128b0d803e8899123). Remapping ports of one to the conflicting services resolved this issue. WDYT?

2021-06-06 13:17 UTC, guymguym commented
I think we can't change it like you suggested because the S3 service is expected to serve on 80/443.

2021-06-06 13:18 UTC, guymguym commented
And for that matter, most services would also serve on these ports, so something in the fact that you describe the services hide eachother sounds like a general problem in that environment.

2021-06-06 13:20 UTC, guymguym commented
In this output:
```
➜  kubectl get svc -n noobaa
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                    AGE
noobaa-db     ClusterIP      10.109.71.207   <none>        27017/TCP                                                  43m
noobaa-mgmt   LoadBalancer   10.108.67.165   localhost     80:31958/TCP,443:30708/TCP,8445:31788/TCP,8446:30521/TCP   43m
                                             ^^^^^^^^^     ^^           ^^^
s3            LoadBalancer   10.109.31.193   localhost     80:31648/TCP,443:32350/TCP,8444:30244/TCP,7004:31920/TCP   43m
                                             ^^^^^^^^^     ^^           ^^^
```
the external address to access s3 is localhost:31958 - not localhost:80.

2021-06-06 14:08 UTC, baum commented
> the external address to access s3 is localhost:31958 - not localhost:80.

@guymguym 31958 in the example above is a `nodePort`, accessible within-cluster network only.  LoadBalancer port (external) port is the number before the colon. 

See for instamce this example:
> ➜  k get svc -n noobaa | grep s3
> s3            LoadBalancer   10.99.120.114   localhost    8080:30910/TCP,444:31097/TCP,8444:32672/TCP,7004:31926/TCP  5h13m
> ➜  k get svc -n noobaa s3 -o yaml
> ...
>  - name: s3
>    nodePort: 30910
>   ^^^^^^^^^^^^^
>    port: 8080
>    protocol: TCP
>    targetPort: 6001
...

WDYT?

2021-06-07 08:08 UTC, guymguym commented
Kubernetes has 3 separate network types:

1. Cluster network (or container network) - this is the network where each Pod and Service have an IP. The service port (80/443 in our case) is accessible on the Service cluster IP, or using the service DNS name (s3.noobaa.svc.cluster.local). Pods should listen on `podIP:targetPort`. This network is accessible only to containers running inside the cluster.

2. Node network (or infrastructure network) - this is the network in which each node has an IP. The service nodePort is accessible on this network on any node. Unless you provide any ingress mechanism (see next) this is your only way to connect to the service from the outside.

3. External network - In order to access a service from external network you typically need to define Ingress (or Route for openshift). In those cases Kubernetes doesn't handle the port mapping itself, and the ingress mechanism is responsible to map some external IP:port to the service.

So - I don't know what docker kubernetes does, but we should keep our service ports 80/443.

2021-06-07 09:12 UTC, dannyzaken commented
@Baum, what is the output of noobaa status in the docker k8s case? I think this is what we should fix in cases like this, and not change the ports just to handle this specific case

2021-06-07 11:12 UTC, baum commented
```
➜  noobaa -n noobaa status
INFO[0000] CLI version: 5.7.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.7.0
INFO[0000] operator-image: noobaa/noobaa-operator:5.7.0
INFO[0000] noobaa-db-image: centos/mongodb-36-centos7
INFO[0000] Namespace: noobaa
INFO[0000]
INFO[0000] CRD Status:
INFO[0000] ✅ Exists: CustomResourceDefinition "noobaas.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "backingstores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "namespacestores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "bucketclasses.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbucketclaims.objectbucket.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbuckets.objectbucket.io"
INFO[0000]
INFO[0000] Operator Status:
INFO[0000] ✅ Exists: Namespace "noobaa"
INFO[0000] ✅ Exists: ServiceAccount "noobaa"
INFO[0000] ✅ Exists: Role "noobaa"
INFO[0000] ✅ Exists: RoleBinding "noobaa"
INFO[0000] ✅ Exists: ClusterRole "noobaa.noobaa.io"
INFO[0000] ✅ Exists: ClusterRoleBinding "noobaa.noobaa.io"
INFO[0000] ✅ Exists: Deployment "noobaa-operator"
INFO[0000]
INFO[0000] System Status:
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: StatefulSet "noobaa-core"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Service "s3"
INFO[0000] ✅ Exists: StatefulSet "noobaa-db"
INFO[0000] ✅ Exists: Service "noobaa-db"
INFO[0000] ✅ Exists: Secret "noobaa-server"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-endpoints"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✅ Exists: Secret "noobaa-root-master-key"
INFO[0000] ✅ Exists: StorageClass "noobaa.noobaa.io"
INFO[0000] ✅ Exists: BucketClass "noobaa-default-bucket-class"
INFO[0000] ✅ Exists: Deployment "noobaa-endpoint"
INFO[0000] ✅ Exists: HorizontalPodAutoscaler "noobaa-endpoint"
INFO[0000] ✅ (Optional) Exists: BackingStore "noobaa-default-backing-store"
INFO[0002] ⬛ (Optional) CRD Unavailable: CredentialsRequest "noobaa-aws-cloud-creds"
INFO[0004] ⬛ (Optional) CRD Unavailable: CredentialsRequest "noobaa-azure-cloud-creds"
INFO[0004] ⬛ (Optional) Not Found: Secret "noobaa-azure-container-creds"
INFO[0004] ⬛ (Optional) Not Found: Secret "noobaa-gcp-bucket-creds"
INFO[0005] ⬛ (Optional) CRD Unavailable: CredentialsRequest "noobaa-gcp-cloud-creds"
INFO[0007] ⬛ (Optional) CRD Unavailable: PrometheusRule "noobaa-prometheus-rules"
INFO[0009] ⬛ (Optional) CRD Unavailable: ServiceMonitor "noobaa-mgmt-service-monitor"
INFO[0011] ⬛ (Optional) CRD Unavailable: ServiceMonitor "s3-service-monitor"
INFO[0013] ⬛ (Optional) CRD Unavailable: Route "noobaa-mgmt"
INFO[0015] ⬛ (Optional) CRD Unavailable: Route "s3"
INFO[0015] ✅ Exists: PersistentVolumeClaim "db-noobaa-db-0"
INFO[0015] ✅ System Phase is "Ready"
INFO[0015] ✅ Exists:  "noobaa-admin"

#------------------#
#- Mgmt Addresses -#
#------------------#

ExternalDNS : [https://localhost:443]
ExternalIP  : []
NodePorts   : [https://192.168.65.4:31024]
InternalDNS : [https://noobaa-mgmt.noobaa.svc:443]
InternalIP  : [https://10.100.215.32:443]
PodPorts    : [https://10.1.0.7:8443]

#--------------------#
#- Mgmt Credentials -#
#--------------------#

email    : admin@noobaa.io
password : 7RWABEILa7nG9Yq8jzJipg==

#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [https://localhost:443]
ExternalIP  : []
NodePorts   : [https://192.168.65.4:31249]
InternalDNS : [https://s3.noobaa.svc:443]
InternalIP  : [https://10.111.255.247:443]
PodPorts    : [https://10.1.0.9:6443]

#------------------#
#- S3 Credentials -#
#------------------#

AWS_ACCESS_KEY_ID     : mEGn7lznjpTCFyuUF3bM
AWS_SECRET_ACCESS_KEY : KPwXaG4s0K4VajGPjrHMEG8COovKoPPjwu3o3fz5

#------------------#
#- Backing Stores -#
#------------------#

NAME                           TYPE      TARGET-BUCKET   PHASE   AGE
noobaa-default-backing-store   pv-pool                   Ready   2m2s

#------------------#
#- Bucket Classes -#
#------------------#

NAME                          PLACEMENT                                                        NAMESPACE-POLICY   PHASE   AGE
noobaa-default-bucket-class   {"tiers":[{"backingStores":["noobaa-default-backing-store"]}]}   null               Ready   2m2s

#-----------------#
#- Bucket Claims -#
#-----------------#

No OBCs found.


```

2021-06-08 10:14 UTC, baum commented
@guymguym @dannyzaken thank you for looking into this issue.

Following discussions, this appears to be a corner case, specific to the Docker Desktop Kubernetes platform. 
I would not mind this issue being documented and this PR closed.

2021-06-08 16:52 UTC, closed without merging